(() => {
  const cfg=window.APP_CONFIG||{}; const view=document.getElementById('admin-view'); const countEl=document.getElementById('admin-listeners');
  const sb=window.supabase?.createClient(cfg.SUPABASE_URL||'',cfg.SUPABASE_ANON_KEY||''); const slug=cfg.SESSION_SLUG||'main';
  let session=null,tracks=[],channel=null;
  function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function t(x,f){return x[`${f}_en`]||x[`${f}_es`]||'';}
  async function init(){ if(!sb){error('Configura config.js.');return;} const {data:{session:s}}=await sb.auth.getSession(); if(!s){renderLogin();return;} await load(); subscribe(); presence(); }
  function error(m){view.innerHTML=`<div class="admin-login"><div class="notice error">${esc(m)}</div></div>`;}
  function renderLogin(){view.innerHTML=`<section class="admin-login"><div class="kicker">ADMIN</div><h1>Sign in</h1><form id="login" class="form-grid"><input type="email" name="email" required placeholder="Email"><input type="password" name="password" required placeholder="Password"><button class="submit">Sign in</button></form><p class="meta">The account must also exist in the <code>admins</code> table.</p></section>`;document.getElementById('login').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);const {error}=await sb.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error)errorBox(error.message);else init();};}
  function errorBox(m){const n=document.querySelector('.notice');if(n)n.textContent=m;else view.insertAdjacentHTML('afterbegin',`<div class="notice error">${esc(m)}</div>`);}
  async function load(){const [a,b]=await Promise.all([sb.from('session_state').select('*').eq('slug',slug).single(),sb.from('tracks').select('*').order('position')]);if(a.error||b.error){error((a.error||b.error).message);return;}session=a.data;tracks=b.data;render();}
  function subscribe(){if(channel)sb.removeChannel(channel);channel=sb.channel(`admin-${slug}`).on('postgres_changes',{event:'*',schema:'public',table:'session_state'},p=>{session=p.new;render();}).subscribe();}
  function presence(){const ch=sb.channel(`listeners-${slug}`,{config:{presence:{key:'admin-'+crypto.randomUUID()}}});ch.on('presence',{event:'sync'},()=>{countEl.textContent=`${Object.keys(ch.presenceState()).length} listeners`}).subscribe();}
  function render(){const current=tracks.find(x=>x.position===session.current_position);view.innerHTML=`<section class="admin-panel"><div class="grid-head"><div><div class="kicker">ADMIN</div><h2>Session control</h2></div><button id="logout" class="text-button">Sign out</button></div><div class="admin-dashboard"><div class="notice">Status: <strong>${esc(session.status)}</strong> · Current position: <strong>${session.current_position||0}</strong> / ${tracks.length}</div>${current?`<div class="admin-current"><img src="${esc(current.cover_url)}"><div><div class="kicker">NOW PLAYING · ${current.position}</div><h2>${esc(t(current,'title'))}</h2><div>${esc(t(current,'artist'))}</div></div></div>`:''}<div class="admin-controls"><button data-action="start">Start</button><button data-action="prev">← Previous</button><button data-action="next">Next →</button><button data-action="end" class="danger">End session</button></div><div class="admin-list">${tracks.map(x=>`<div class="admin-row"><span class="num">${String(x.position).padStart(2,'0')}</span><img src="${esc(x.cover_url)}"><div class="title">${esc(t(x,'artist'))}<br><small>${esc(t(x,'title'))}</small></div><button data-jump="${x.position}">Jump</button></div>`).join('')}</div></div></section>`;bind();}
  async function update(p,status=null){const patch={current_position:p};if(status)patch.status=status;const {error}=await sb.from('session_state').update(patch).eq('slug',slug);if(error)alert(error.message);}
  function bind(){document.getElementById('logout').onclick=async()=>{await sb.auth.signOut();renderLogin();};document.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{const a=b.dataset.action;if(a==='start')await update(1,'live');if(a==='prev')await update(Math.max(1,(session.current_position||1)-1),'live');if(a==='next')await update(Math.min(tracks.length,(session.current_position||0)+1),'live');if(a==='end')await update(session.current_position||tracks.length,'finished');});document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>update(Number(b.dataset.jump),'live'));}
  init();
})();
